In [2]:
# 넘파이 라이브러리를 불러옵니다. numpy는 np로 축약해서 사용합니다.
import numpy as np

In [3]:
# 넘파이 배열 생성합니다. ‼️파이썬 기본 자료구조와는 다른 데이터 타입입니다.
# 1차원 배열이 3개, 2차원 배열이 5개의 🧡값🧡을 가지는 15개의 숫자를 생성합니다.
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# 넘파이 배열 정보 확인하기
# 넘파이 배열의 차원 확인하기
arr1.shape

(3, 5)

In [5]:
# 넘파이 배열의 데이터 타입 확인하기 -> 판다스와 동일함
arr1.dtype

dtype('int64')

In [7]:
# 1차원 배열이 3개, 2차원 배열이 4개인 🧡0으로 채워진🧡 넘파이 배열을 생성하기
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# 넘파이 배열에서 데이터 연산 하기
arr4 = np.array([
    [1,2,3],
    [4,5,6]
], dtype = np.float64)

arr5 = np.array([
    [7,8,9],
    [10,11,12]
], dtype = np.float64)

# 사칙 연산
print(arr4 + arr5, "\n") # arr4와 arr5를 더합니다.
print(arr4 - arr5, "\n") # arr4와 arr5를 뺍니다.
print(arr4 * arr5, "\n") # arr4와 arr5를 곱합니다.
print(arr4 / arr5, "\n") # arr4와 arr5를 나눕니다.

[[ 8. 10. 12.]
 [14. 16. 18.]] 

[[-6. -6. -6.]
 [-6. -6. -6.]] 

[[ 7. 16. 27.]
 [40. 55. 72.]] 

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] 

